### ISSUE TITLE
plan for releasing dataset (HAT, nocaps-FOIL) 

### ISSUE THREAD

**Issue by long8v** [DavidMChan/aloha#1]
Thank you for your great work! 
I was wondering if you might have any plans to release the test set for the HAT and nocaps-FOIL datasets? Access to those test sets would be incredibly helpful for the research I'm currently conducting. I would greatly appreciate any information you're able to provide. Thank you in advance for your consideration.

**Comment by DavidMChan** [comment]
Thanks for reaching out! 

The HAT trainval set which we used for the paper is already available here: https://github.com/DavidMChan/aloha/blob/main/data/hat-trainval.json 

The nocaps FOIL validation dataset which we used for the paper is available here:
[nocaps-val-foil.json](https://github.com/user-attachments/files/15824094/nocaps-val-foil.json)

Feel free to reach out if there are other dataset artifacts you are interested in!

**Comment by long8v** [comment]
Thank you for super quick response! 😄 
In addition, I was wondering if it would be possible to also obtain the test sets for the HAT and nocaps-FOIL datasets.
Based on the table captions, it seems Table 1 refers to the HAT test set, and Table 2 likely uses the test sets as well. (since FOIL dataset does not have valid split as far as I know)

**Comment by DavidMChan** [comment]
Sorry for the confusion. To clarify, these two files are the test sets used in the paper - it is just a naming inconsistency (as there is additional HAT data that we are not releasing at this time).

**Comment by long8v** [comment]
I think `nocaps-val-foil.json` you provided in issue is the data used in paper, which has 2500 instances. but https://github.com/DavidMChan/aloha/blob/main/data/hat-trainval.json dataset only has 82 instance when I open it, while paper says test set 400 instances. Can you check whether I went wrong?

**Comment by DavidMChan** [comment]
Whoops! Looks like I uploaded a subset of the full dataset. The correct set is here (and I've updated the released JSONs):

[hat-trainval.json](https://github.com/user-attachments/files/15840785/hat-trainval.json)

**Comment by long8v** [comment]
Thank you so much!!!! 😄

**Comment by long8v** [comment]
Just to be clear, to estimate AP, is it right to use `nocaps-val-foil.json` once with "foil" and once with "baseline"(not foil) so that ratio between FOIL and not FOIL would be 1:1?
