### ISSUE TITLE
HAT Dataset

### ISSUE THREAD

**Issue by BrianG13** [DavidMChan/aloha#3]
Hi,

Thank you for sharing your work! 

I am wondering if the HAT dataset is available.

Thanks!

**Comment by DavidMChan** [comment]
The HAT dataset is already available in the github repo here: https://github.com/DavidMChan/aloha/blob/e38d69e0004a044254cef2641985c7ae4e01efd4/data/hat-trainval.json

We are working to add some documentation, and will update the documentation when it becomes available.
