### ISSUE TITLE
Error of missing files: chair-nocaps using aloha package

### ISSUE THREAD

**Issue by youthHan** [DavidMChan/aloha#5]
Hi, thank you for releasing this project. I encountered with the error of missing `nocaps_acceptable.txt` and `nocaps_synonyms.txt`, when using metric chair-nocaps. Can you please provide the files or instructions on how to generate them?

**Comment by DavidMChan** [comment]
Sorry for the oversight! Here are the files:

[nocaps_acceptable.txt](https://github.com/user-attachments/files/16336881/nocaps_acceptable.txt)
[nocaps_synonyms.txt](https://github.com/user-attachments/files/16336884/nocaps_synonyms.txt)
